import sharp from 'sharp'
import JSZip from 'jszip'
import pngToIco from 'png-to-ico'
import { vectorizeLogo } from '@/lib/vectorization'
import { extractPalette, renderPaletteImage } from './palette'

/**
 * Brand kit builder: one source logo PNG in → a ready-to-use ZIP out.
 * Logo sizes, favicon set (incl. .ico), social banners, SVG vector,
 * color palette, and a README. Pure function over buffers — the API route
 * handles fetching/uploading.
 */

const LOGO_SIZES = [1024, 512, 256, 128] as const
const FAVICON_SIZES = [16, 32, 48, 180, 192, 512] as const

const SOCIAL_CANVASES = [
  { file: 'og-image-1200x630.png', width: 1200, height: 630 },
  { file: 'x-header-1500x500.png', width: 1500, height: 500 },
  { file: 'linkedin-banner-1584x396.png', width: 1584, height: 396 },
  { file: 'profile-400x400.png', width: 400, height: 400 },
] as const

const TRANSPARENT = { r: 0, g: 0, b: 0, alpha: 0 }

function squareLogo(png: Buffer, size: number): Promise<Buffer> {
  return sharp(png)
    .resize(size, size, { fit: 'contain', background: TRANSPARENT })
    .png()
    .toBuffer()
}

/** Logo centered on a white canvas at ~55% of the canvas height. */
async function socialCanvas(png: Buffer, width: number, height: number): Promise<Buffer> {
  const logoHeight = Math.round(height * 0.55)
  const logo = await sharp(png)
    .resize(width, logoHeight, { fit: 'inside', background: TRANSPARENT })
    .png()
    .toBuffer()

  return sharp({ create: { width, height, channels: 4, background: '#ffffff' } })
    .composite([{ input: logo, gravity: 'center' }])
    .png()
    .toBuffer()
}

function buildReadme(brandName: string, colors: string[]): string {
  return `# ${brandName} — Brand Kit

Generated by v0 Prompts Genie.

## Contents

- **logo/** — your logo as a transparent PNG at 1024/512/256/128 px, the
  original file, and a scalable SVG vector (logo.svg).
- **favicon/** — favicon.ico (16+32+48) plus the PNG set modern browsers
  and phones use: 16, 32, 48, 180 (apple-touch-icon), 192 and 512
  (android-chrome).
- **social/** — ready-made canvases: Open Graph link preview (1200×630),
  X/Twitter header (1500×500), LinkedIn banner (1584×396), and a square
  profile picture (400×400).
- **colors/** — your brand palette as a swatch image and the hex codes
  below.

## Brand colors

${colors.map((c) => `- \`${c}\``).join('\n')}

## Favicon snippet

\`\`\`html
<link rel="icon" href="/favicon.ico" sizes="48x48">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
\`\`\`
`
}

export interface BrandKitResult {
  zip: Buffer
  colors: string[]
}

export async function buildBrandKit(sourcePng: Buffer, brandName: string): Promise<BrandKitResult> {
  // Normalize the source once; everything else derives from it.
  const original = await sharp(sourcePng).ensureAlpha().png().toBuffer()
  const zip = new JSZip()

  zip.file('logo/logo-original.png', original)
  for (const size of LOGO_SIZES) {
    zip.file(`logo/logo-${size}.png`, await squareLogo(original, size))
  }

  // SVG vector — best-effort: a vectorizer failure shouldn't sink the kit.
  try {
    zip.file('logo/logo.svg', await vectorizeLogo(original))
  } catch (error) {
    console.error('[brand-kit] vectorization failed, kit ships without SVG:', error)
  }

  const faviconPngs: Record<number, Buffer> = {}
  for (const size of FAVICON_SIZES) {
    faviconPngs[size] = await squareLogo(original, size)
  }
  zip.file('favicon/favicon-16.png', faviconPngs[16])
  zip.file('favicon/favicon-32.png', faviconPngs[32])
  zip.file('favicon/favicon-48.png', faviconPngs[48])
  zip.file('favicon/apple-touch-icon.png', faviconPngs[180])
  zip.file('favicon/android-chrome-192.png', faviconPngs[192])
  zip.file('favicon/android-chrome-512.png', faviconPngs[512])
  try {
    zip.file('favicon/favicon.ico', await pngToIco([faviconPngs[16], faviconPngs[32], faviconPngs[48]]))
  } catch (error) {
    console.error('[brand-kit] favicon.ico failed, PNG set still included:', error)
  }

  for (const canvas of SOCIAL_CANVASES) {
    zip.file(`social/${canvas.file}`, await socialCanvas(original, canvas.width, canvas.height))
  }

  const colors = await extractPalette(original)
  zip.file('colors/palette.png', await renderPaletteImage(colors))
  zip.file(
    'colors/colors.md',
    `# ${brandName} colors\n\n${colors.map((c) => `- ${c}`).join('\n')}\n`,
  )

  zip.file('README.md', buildReadme(brandName, colors))

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
  return { zip: zipBuffer, colors }
}
