"use client"

import { useState } from 'react'
import dynamic from 'next/dynamic'
import { Box, Loader2, RotateCcw, TriangleAlert, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { BACKGROUND_OPTIONS, LogoSpin3DControls, type SpinSettings } from './LogoSpin3DControls'
import { useLogoSvg } from './useLogoSvg'

/**
 * 3D spin preview for a generated logo.
 *
 * Geometry is extruded from the logo's own vector paths rather than generated by
 * an image-to-3D model, so letterform edges stay exact and there are no invented
 * back faces. Preview only — export is a separate issue.
 *
 * The WebGL half is loaded on demand: three plus the scene is a large chunk, and
 * users who never open this panel should not pay for it (AC-8). `ssr: false`
 * because there is no WebGL context on the server.
 */
const LogoSpinScene = dynamic(() => import('./LogoSpinScene'), {
  ssr: false,
  loading: () => (
    <div className="flex h-full items-center justify-center">
      <Loader2 className="h-6 w-6 animate-spin text-[#dbb56e]" />
    </div>
  ),
})

const DEFAULT_SETTINGS: SpinSettings = {
  level: 'medium',
  bevelEnabled: true,
  material: 'metallic',
  axis: 'y',
  speed: 1,
  backgroundId: 'dark',
}

interface LogoSpin3DModalProps {
  isOpen: boolean
  onClose: () => void
  /** URL of the logo to extrude; vectorized on demand. */
  logoUrl: string | null
}

export function LogoSpin3DModal({ isOpen, onClose, logoUrl }: LogoSpin3DModalProps) {
  const [settings, setSettings] = useState<SpinSettings>(DEFAULT_SETTINGS)
  const { svg, isLoading, error, retry } = useLogoSvg(logoUrl, isOpen)

  if (!isOpen) return null

  const background = BACKGROUND_OPTIONS.find((option) => option.id === settings.backgroundId)?.value ?? null
  const patchSettings = (patch: Partial<SpinSettings>) => setSettings((current) => ({ ...current, ...patch }))

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4">
      <Card className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden border-[#c99850]/30 bg-zinc-900">
        <div className="flex items-center justify-between gap-4 border-b border-zinc-800 p-4">
          <div className="flex items-center gap-2">
            <Box className="h-5 w-5 text-[#dbb56e]" />
            <div>
              <h2 className="text-xl font-bold text-white">3D Spin</h2>
              <p className="text-xs text-zinc-400">Your logo extruded from its own vector paths</p>
            </div>
          </div>

          <Tooltip>
            <TooltipTrigger asChild>
              <Button onClick={onClose} size="sm" variant="ghost" className="text-zinc-400 hover:text-white">
                <X className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">Close</TooltipContent>
          </Tooltip>
        </div>

        <div className="flex flex-1 flex-col gap-4 overflow-y-auto p-4 md:flex-row">
          {/*
            A definite height, not just min-h + flex-1. r3f sizes its canvas from
            the parent box, and a flex child with only an intrinsic height inside a
            scrolling column can resolve to zero — the canvas then falls back to its
            300x150 default and the logo looks missing rather than broken.
          */}
          <div className="h-[420px] w-full shrink-0 overflow-hidden rounded-lg border border-zinc-800 bg-zinc-950 md:h-[520px] md:flex-1">
            {isLoading && (
              <div className="flex h-full flex-col items-center justify-center gap-2">
                <Loader2 className="h-6 w-6 animate-spin text-[#dbb56e]" />
                <p className="text-xs text-zinc-500">Tracing the logo&rsquo;s vector paths&hellip;</p>
              </div>
            )}

            {!isLoading && error && (
              <div className="flex h-full flex-col items-center justify-center gap-3 p-6 text-center">
                <TriangleAlert className="h-8 w-8 text-red-400" />
                <p className="max-w-sm text-sm text-zinc-300">{error}</p>
                <Button
                  onClick={retry}
                  size="sm"
                  variant="ghost"
                  className="border border-zinc-800 text-zinc-300 hover:text-white"
                >
                  <RotateCcw className="mr-2 h-4 w-4" />
                  Try again
                </Button>
              </div>
            )}

            {!isLoading && !error && svg && (
              <LogoSpinScene
                svg={svg}
                level={settings.level}
                bevelEnabled={settings.bevelEnabled}
                material={settings.material}
                axis={settings.axis}
                speed={settings.speed}
                background={background}
              />
            )}

            {!isLoading && !error && !svg && !logoUrl && (
              <div className="flex h-full items-center justify-center p-6 text-center">
                <p className="text-sm text-zinc-500">Generate a logo first, then spin it.</p>
              </div>
            )}
          </div>

          <div className="w-full shrink-0 md:w-64">
            <LogoSpin3DControls settings={settings} onChange={patchSettings} />
          </div>
        </div>
      </Card>
    </div>
  )
}
